docs: :memo: Add section about gradle build error
docToolchain/docToolchain pull request #807
Opened 2022-02-27 14:57 UTC by faltfe

In some CI environments permissions are restricted and gradle can not build the project from the docker image using the volume '-v '${PWD}:/project''

### All Submissions:

* [ ] Did you update the `changelog.adoc`?
* [x] Does your PR affect the documentation?
* [x] If yes, did you update the documentation ~or create an issue for updating it~?

The source of the documentation can be found in `/src/docs/`.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [ ] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

inspiration: https://github.com/stevemao/github-issue-templates

2022-03-02 20:52 UTC, rdmueller commented
thanx for this update to the docs. I wonder if we can also change the code in such a way that we can display a hint 🤔?

2022-07-20 06:30 UTC, JodyWinter requested changes

2022-07-20 06:30 UTC, JodyWinter commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
> +=== I get an error 'Failed to create parent directory /project/.gradle'
I get a `Failed to create parent directory /project/.gradle` error

2022-07-20 06:30 UTC, JodyWinter commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
> +This issue might occure in CI enviroments (e.g. Bamboo) with resticted permissions in the working folder where files or directories created outside the container might not be accessible inside the co
This issue can occur in CI enviroments (such as Bamboo) that have resticted permissions in the working folder where files or directories created outside the container might not be accessible inside the container. Before starting the container, give the working directory maximum permissions for allowing access to the user inside the Docker container.

2022-07-20 06:30 UTC, JodyWinter commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
>  === Q: I get an error that Gradle dependencies cannot be downloaded because a proxy is restricting internet access.
I get an error stating that Gradle dependencies cannot be downloaded because a proxy is restricting internet access

2022-08-02 19:40 UTC, jmini commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
>  === Q: I get an error that Gradle dependencies cannot be downloaded because a proxy is restricting internet access.
Solved with  ec27325

2022-08-02 19:40 UTC, jmini commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
> +This issue might occure in CI enviroments (e.g. Bamboo) with resticted permissions in the working folder where files or directories created outside the container might not be accessible inside the co
Solved with  ec27325

2022-08-02 19:41 UTC, jmini commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
> +=== I get an error 'Failed to create parent directory /project/.gradle'
Solved with  ec27325

2022-08-02 19:45 UTC, jmini commented
@JodyWinter I have made the requested changes in ec27325

Feel free to use the "Suggesting Changes" feature (point `(6)` in [Adding line comments to a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request)), it make it easier to apply the suggested changes.

2022-08-03 06:19 UTC, jmini commented on src/docs/010_manual/50_Frequently_asked_Questions.adoc
> +=== I get a `Failed to create parent directory /project/.gradle` error
Add missing Q to be consistent:

```suggestion
=== Q: I get a `Failed to create parent directory /project/.gradle` error
```

2022-08-03 07:31 UTC, JodyWinter commented
> @JodyWinter I have made the requested changes in [ec27325](https://github.com/docToolchain/docToolchain/commit/ec273252d8bd614bb53ef30e567f99076473027b)
> 
> Feel free to use the "Suggesting Changes" feature (point `(6)` in [Adding line comments to a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request)), it make it easier to apply the suggested changes.

Thank you @jmini I will do that next time.

2022-08-03 11:08 UTC, rdmueller commented
hm. I think netlify fails because of a recent change I made to the netlify scripts. So we should ignore this for now.

regarding the other changes - this is ready to be merged?

2022-08-03 20:26 UTC, JodyWinter commented
> 

Yes it can be merged.

2022-08-03 20:44 UTC, merged